### ISSUE TITLE
Show multiple speaker images in schedule view

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX-Devoxx-2019-BE#2]
**Is your feature request related to a problem? Please describe.**
At the moment only one speaker image is shown, although more speakers may be participating in the session.

**Describe the solution you'd like**
Create an overlapping view of speaker images or create any type of animation to show all speaker images at the same place.

**Comment by mklaehn** [comment]
relates to TweetWallFX/TweetwallFX#916
