### ISSUE TITLE
Add more details to tweet in infinite stream view

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX-Devoxx-2019-BE#29]
**Is your feature request related to a problem? Please describe.**
Not all tweet meta data is shown, e.g. fav count, creation date are missing from the view.

**Describe the solution you'd like**
Add the relevant meta data to the view and add configuration possibility if they should be shown or not.

**Comment by mklaehn** [comment]
Without displaying retweeted tweets it will not be desirable to show favorites and retweet count.
This leaves the creation time in e.g. a natural formatting (e.g. 13 minutes ago)
