### ISSUE TITLE
Add fav counts to schedule view

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX-Devoxx-2019-BE#33]
**Is your feature request related to a problem? Please describe.**
Fav counts are not visible in the displayed schedule. Would be good to have this information at hand.

**Describe the solution you'd like**
Add fav count to the session ui, make display configurable.

**Comment by mklaehn** [comment]
depends on TweetWallFX/TweetwallFX#935

**Comment by mklaehn** [comment]
depends on #46 for actua values for the favorites count
